[workspace]
members = [
    "api/apiserver",
    "api/apiclient",
    "api/bork",
    "api/early-boot-config",
    "api/netdog",
    "api/sundog",
    "api/schnauzer",
    "api/pluto",
    "api/servicedog",
    "api/host-containers",
    "api/storewolf",
    "api/thar-be-settings",
    "api/thar-be-updates",
    "api/settings-committer",
    "api/migration/migrator",
    "api/migration/migration-helpers",

    # "api/migration/migrations/vX.Y.Z/...
    "api/migration/migrations/v0.3.2/migrate-admin-container-v0-5-0",
    "api/migration/migrations/v0.4.1/add-version-lock-ignore-waves",
    "api/migration/migrations/v0.4.1/healthdog-init",
    "api/migration/migrations/v0.4.1/pivot-repo-2020-07-07",

    "bottlerocket-release",

    "growpart",

    "healthdog",

    "logdog",

    "models",

    "parse-datetime",

    "updater/block-party",
    "updater/signpost",
    "updater/update_metadata",
    "updater/updog",

    "webpki-roots-shim",
]

[profile.release]
debug = true

# This replaces webpki-roots with a shim that reads from the ca-certificates package
[patch.crates-io.webpki-roots]
path = "webpki-roots-shim"
