# The following represents a "normal" set of update waves for a typical
# deployment. The deployment lasts for 6 days, and gradually increases the
# nodes updated at once.
[[waves]]
start_after = '1 hour'
fleet_percentage = 1

[[waves]]
start_after = '4 hours'
fleet_percentage = 5

[[waves]]
start_after = '1 day'
fleet_percentage = 15

[[waves]]
start_after = '2 days'
fleet_percentage = 40

[[waves]]
start_after = '4 days'
fleet_percentage = 60

[[waves]]
start_after = '5 days'
fleet_percentage = 90

# Last 10 percent of the hosts will update immediately after 6 days since the start of
# deployment. Unlike the other waves, there will be no velocity control.
[[waves]]
start_after = '6 days'
fleet_percentage = 100
