[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_15"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.15"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.15.10/kubernetes-1.15.10.tar.gz"
sha512 = "48c069d88a0111072ac02aed0760bc34ae44fbb5140489a837f089a6c944b5fa18f95f4bcc4286ca1fdfd6cd25e7bd0ff99c3b21373a1d70d3a0f70d352d4ed8"

[build-dependencies]
glibc = { path = "../glibc" }
