[clarify."github.com/JeffAshton/win_pdh"]
expression = "BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xb221dcc9 },
]

[clarify."github.com/daviddengcn/go-colortext"]
expression = "BSD-3-Clause AND MIT"
license-files = [
    { path = "LICENSE", hash = 0x9769fae1 },
]

[clarify."github.com/ghodss/yaml"]
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xcdf3ae00 },
]

[clarify."github.com/heketi/heketi"]
# kubernetes only uses code that is under LGPLv3+/Apache 2.0, not the code that is GPLv2+/LGPLv3+
expression = "LGPL-3.0-or-later OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x3c4b96d1 },
    { path = "LICENSE-APACHE2", hash = 0x438c8616 },
    { path = "COPYING-LGPLV3", hash = 0xf0bccb3a },
]
skip-files = [ "COPYING-GPLV2" ]

[clarify."github.com/jteeuwen/go-bindata"]
expression = "CC0-1.0"
license-files = [
    { path = "LICENSE", hash = 0x393fafd6 },
]

[clarify."github.com/miekg/dns"]
expression = "BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0xe41dd36c },
    { path = "LICENSE", hash = 0xbd510d7b },
]

[clarify."github.com/munnerz/goautoneg"]
# license file was added later, see https://github.com/munnerz/goautoneg/commit/69886a7167b7b3d629d0e3db7c3a78dc8dc1e248
expression = "BSD-3-Clause"
license-files = []

[clarify."sigs.k8s.io/yaml"]
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xcdf3ae00 },
]
