[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
imdsclient = { path = "../../imdsclient" }
models = { path = "../../models" }
rusoto_core = { version = "0.46", default-features = false, features = ["rustls"] }
rusoto_eks = { version = "0.46", default-features = false, features = ["rustls"] }
serde_json = "1"
snafu = "0.6"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cargo-readme = "3.1"
